apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todolist
spec:
  selector:
    matchLabels:
      run: my-todolist
  replicas: 3
  template:
    metadata:
      labels:
        run: my-todolist
    spec:
      containers:
      - name: my-todolist
        image: gcr.io/gke-cicd-arctiq/todolist:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-todolist
  labels:
    run: my-todolist
spec:
  ports:
  - port: 3000
    protocol: TCP
  type: LoadBalancer
  selector:
    run: my-todolist