apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gcp-trial-86/argo-cd-example.git
    targetRevision: HEAD
    path: manifests/nginx
  destination:
    server: gke_gke-cicd-arctiq_us-east1_gke-cicd-arctiq-gke
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
